### ISSUE TITLE
ERROR in Ngrok line 412

### ISSUE THREAD

**Issue by ashish-singh-bora** [EricksonAtHome/blackeye#18]
After cloning BLACKEYE in my local machine  
I tried to use it but after selecting option 1 for instagram it shows me two option 1.Ngrok  2.Localtunnel
I selected option 1 then it gives me this ERROR (picture attached below)
![Screenshot from 2024-02-23 15-11-50](https://github.com/EricksonAtHome/blackeye/assets/135435891/fc651da3-7cd6-412c-aed2-b4063a7fd7cd)

`

 ┌─[ Choose an option:]─[~]
 └──╼ ~ 1

1.Ngrok
2.Localtunnel

 ┌─[ Choose the tunneling method:]─[~]
 └──╼ ~ 1

[*] Starting php server...
[*] Starting ngrok server...
[*] Send this link to the Victim: 
blackeye.sh: line 412: jq: command not found
blackeye.sh: line 412: xsel: command not found
blackeye.sh: line 412: xsel: command not found
[*] Use shortened link instead: 

[*] Waiting victim open the link ...

`
It's showing that line 412:jq, 412:xsel, 412:xsel. command not found
![Screenshot from 2024-02-23 15-11-50](https://github.com/EricksonAtHome/blackeye/assets/135435891/498ea8e8-ad8e-45e8-8e37-4a83e34ebe59)

As for my System Information 
![Uploading Screenshot from 2024-02-23 15-16-54.png…]()

**Comment by ashish-singh-bora** [comment]
As for my System information 
![Uploading Screenshot from 2024-02-23 15-16-54.png…]()

**Comment by BoujeeRichie** [comment]
@Amalrajraju Hey can i pay you to create one for me?

**Comment by ashish-singh-bora** [comment]
okay how much will you pay?

**Comment by BoujeeRichie** [comment]
> okay how much will you pay?
> […](#)

Email me theboujeerichie@outlook.com or send me your email instead.
Let me know your budget

**Comment by Oks-pro1** [comment]
Please I need the phishing link.
